# Fill in your hosts, users and passwords
# Enabled field specifies, if corresponding pod should be created

carbonLTS:
  enabled: false

graphiteLTS:
  enabled: false

zookeeper:
  enabled: false

clickhousefront: # For front clickhouse installation
  enabled: false
  user: "demo"
  pass: "demo"
  serverNodePort: 30010
  clientNodePort: 30011

  # Optional node selector. Specify yours, or leave it blank
  #nodeSelector: {
  #  task: "clickhouse" 
  #}

clickhouse: # For local clickhouse installation
  enabled: false
  user: "demo"
  pass: "demo"
  serverNodePort: 30010
  clientNodePort: 30011

  # Optional node selector. Specify yours, or leave it blank
  #nodeSelector: {
  #  task: "clickhouse" 
  #}

grafana:
  enabled: true
  #serverNodePort: 30012 # Optional
  user: "admin" # Default user, that will be assigned while starting pod
  pass: "admin" # Default pass, that will be assigned while starting pod
  
  # Optional node selector. Specify yours, or leave it blank
  #nodeSelector: {
  #  task: "bench" 
  #}

prometheus:
  enabled: false
  serverNodePort: 30013
  folderId: "b1gvpjv4qrkefqc2d8go"
  serviceCH: "managed-clickhouse"
  serviceCompute: "compute"
  serviceKubernetes: "managed-kubernetes"
  token: "AQVNww9yLAtcj7qRjJtgz8Ff94CxGzxbyQS2Hvl5"

  # Optional node selector. Specify yours, or leave it blank
  #nodeSelector: {
  #  task: "bench" 
  #}

nodeexporter:
  enabled: false
  serverNodePort: 30014

  # Optional node selector. Specify yours, or leave it blank
  #nodeSelector: {
  #  task: "clickhouse" 
  #}

carbon:
  clickhouse: # Your clickhoure credentials. Fill in, if you have are using not local cluster for tests 
    user: admin # Specify clickhouse user
    pass: "hilbert123" # Specify clickhouse pass
    host: "rc1a-ubp4bu60luehmnti.mdb.yandexcloud.net" # Specify clickhouse URL  (Direct shard/proxy url/front-server url)

    #Direct to shard
    #host: "rc1a-okgvsvhllaskgnnv.mdb.yandexcloud.net" # Specify clickhouse URL  (or proxy url/front-server url)
    protocol: "https"
    port: 8443

    # Optional node selector. Specify yours, or leave it blank
    #nodeSelector: {
    #  task: "bench" 
    #}

  enabled: true

graphite:
  clickhouse: # Your clickhoure credentials. Fill in, if you have are using not local cluster for tests 
    user: admin # Specify clickhouse user
    pass: "hilbert123" # Specify clickhouse pass
    host: "rc1a-ubp4bu60luehmnti.mdb.yandexcloud.net" # Specify clickhouse URL (or proxy url)
    protocol: "https"
    port: 8443

    # Optional node selector. Specify yours, or leave it blank
    #nodeSelector: {
    #  task: "bench" 
    #}

  enabled: true


qryn: 
  enabled: false
  click:
    user: demo
    password: demo
    port: 8123
    # address: host.mdb.yandexcloud.net
    address: graphite-click-clickhouse-service.click-graphite.svc.cluster.local

  # Optional node selector. Specify yours, or leave it blank
  #nodeSelector: {
  #  task: "clickhouse" 
  #}
