# Fill in your hosts, users and passwords
# Enabled field specifies, if corresponding pod should be created

clickhousefront: # For front clickhouse installation
  enabled: true
  user: "demo"
  pass: "demo"
  serverNodePort: 30010
  clientNodePort: 30011

clickhouse: # For local clickhouse installatiom
  enabled: false
  user: "demo"
  pass: "demo"
  serverNodePort: 30010
  clientNodePort: 30011

grafana:
  enabled: true
  user: "admin" # Default user, that will be assigned while starting pod
  pass: "admin" # Default pass, that will be assigned while starting pod
  serverNodePort: 30012

prometheus:
  enabled: true
  serverNodePort: 30013

nodeexporter:
  enabled: true
  serverNodePort: 30014

carbon:
  clickhouse: # Your clickhoure credentials. Fill in, if you have are using not local cluster for tests 
    user: admin # Specify clickhouse user
    pass: "admin" # Specify clickhouse pass
    #host: "graphite-click-chproxy.click-graphite" # Specify clickhouse URL  (or proxy url)
    host: "mdb.yandexcloud.net" # Specify clickhouse URL  (or proxy url)
    protocol: "https"
    port: 8443
  enabled: true

graphite:
  clickhouse: # Your clickhoure credentials. Fill in, if you have are using not local cluster for tests 
    user: admin # Specify clickhouse user
    pass: "admin" # Specify clickhouse pass
    host: "mdb.yandexcloud.net" # Specify clickhouse URL (or proxy url)
    protocol: "http"
    port: 80
  enabled: false

qryn: 
  enabled: false
  click:
    user: demo
    password: demo
    port: 8123
    # address: host.mdb.yandexcloud.net
    address: graphite-click-clickhouse-service.click-graphite.svc.cluster.local

chproxy: # In case you want to use chproxy to apply balancing on your cluster
  enabled: false

  replicaCount: 5

  image:
    # repository: contentsquareplatform/chproxy

    repository: chproxy 
    # Base chproxy image. If you want to connect strictly with ssl (ex., cloud providers usually have only this options)
    # You might need to create your own custom image and put essentials certs inside it

    # Overrides the image tag whose default is the chart appVersion.
    tag: "v1.25.0"


  serviceAccount:
    # Specifies whether a service account should be created (clour provider)
    create: false


  config: | 
    hack_me_please: true
    log_debug: false
    server:
      http:
        listen_addr: ":80"
    users:
      - name: "admin" # Specify user creds, if you want proxy auth
        password: "admin" # Specify pass creds, if you want proxy auth
        to_user: "admin" # Specify clickhouse user to send data
        to_cluster: "default" # Specify clickhouse cluster, where to send data
    clusters:
      - name: "default" # Specify cluster name
        scheme: "https"
        nodes: [        # Set of nodes to perform LoadBalancing
          "mdb.yandexcloud.net:8443",
        ]
        users:
          - name: "admin" # Specify clickhouse user
            password: "admin" # Specify clickhouse pass
