clickhouse:
  user: "demo"
  pass: "demo"
  serverNodePort: 30010
  clientNodePort: 30011

grafana:
  user: "admin"
  pass: "admin"
  serverNodePort: 30012

prometheus:
  serverNodePort: 30013

nodeexporter:
  serverNodePort: 30014

carbon:
  serverNodePort: 30015

graphite:
  serverNodePort: 30016
