{{- if .Values.carbonLTS.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-carbon-deployment"
spec:
  replicas: 3 #Specify number of replicas 
  selector:
    matchLabels:
      app: carbon-clickhouse
  template:
    metadata:
      labels:
        app: carbon-clickhouse
    spec:
      {{- with $.Values.carbonLTS.clickhouse.nodeSelector }}
      nodeSelector: #In case you need to stick your deployment to specific node for performance/data storage issues
        {{- toYaml . | nindent 8 }}
      {{- end }}
      
      #In case you are using managed solution, you will need to build a custom container, that contains cloud CA - cert, that will allow
      #Incoming traffic to your cluster. Otherwise traffic will not pass.
      #Example below shows one of the way to use it
      #Or you can moint it directly, described it in your deployment (Example shown in graphite)

      containers: 
        - name: carbon-clickhouse
          image: your_custom_container/carbon-clickhouse:v0.11.7
          imagePullPolicy: Always
          volumeMounts:
            - name: carbon-conf
              mountPath: "/etc/carbon-clickhouse"
---
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-carbon-service"
#   namespace: click-graphite
spec:
  type: NodePort
  selector:
    app: carbon-clickhouse
  ports:
    - name: "2006"
      protocol: TCP
      port: 2006
      targetPort: 2006
      nodePort: {{ .Values.carbonLTS.serverNodePort }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-carbon-cm"
#   namespace: click-graphite
data:
  carbon-clickhouse.conf: | #Carbon ClickHouse simple configuration. More info here:
    [common]
    metric-prefix = "stats.carbon_clickhouse.prom.{host}"
    metric-endpoint = "local"
    max-cpu = 2
    metric-interval = "1m"

    [data]
    path = "/data/carbon-clickhouse/"
    compression-level = 0
    chunk-interval = "1s"
    chunk-auto-interval = ""
    compression = "none"

    [upload.graphite]
    type = "points"
    table = "distributed_graphite" #In case you want to write to distributed table
    #table = "graphite" #In case you want to write straight to shard
    zero-timestamp = false
    threads = 1
    url = "{{ .Values.carbonLTS.clickhouse.protocol }}://{{ .Values.carbonLTS.clickhouse.user }}:{{ .Values.carbonLTS.clickhouse.pass }}@{{ .Values.carbonLTS.clickhouse.host }}:{{ .Values.carbonLTS.clickhouse.port }}/"
    timeout = "1m0s"
    # [upload.graphite.tls]
    # ca-cert = ["/usr/share/ca-certificates/Yandex/ca-cert"]
    # server-name = "<server-name>"
    # insecure-skip-verify = true # if true, server certificates will not be validated

    [upload.graphite_index]
    type = "index"
    table = "distributed_graphite_index" #In case you want to write to distributed table
    #table = "graphite_index" #In case you want to write straight to shard
    threads = 1
    url =  "{{ .Values.carbonLTS.clickhouse.protocol }}://{{ .Values.carbonLTS.clickhouse.user }}:{{ .Values.carbonLTS.clickhouse.pass }}@{{ .Values.carbonLTS.clickhouse.host }}:{{ .Values.carbonLTS.clickhouse.port }}/"
    timeout = "1m0s"
    cache-ttl = "12h0m0s"
    # [upload.graphite_index.tls]
    # # ca-cert = [ "/usr/share/ca-certificates/Yandex/ca-cert" ]
    # # server-name = "<server-name>"
    # insecure-skip-verify = true # if true, server certificates will not be validated

    [upload.graphite_tagged]
    type = "tagged"
    table = "distributed_graphite_tagged" #In case you want to write to distributed table
    #table = "graphite_tagged" #In case you want to write straight to shard
    threads = 1
    url = "{{ .Values.carbonLTS.clickhouse.protocol }}://{{ .Values.carbonLTS.clickhouse.user }}:{{ .Values.carbonLTS.clickhouse.pass }}@{{ .Values.carbonLTS.clickhouse.host }}:{{ .Values.carbonLTS.clickhouse.port }}/"
    timeout = "1m0s"
    cache-ttl = "12h0m0s"
    # [upload.graphite_tagged.tls]
    # # ca-cert = [ "/usr/share/ca-certificates/Yandex/ca-cert" ]
    # # server-name = "<server-name>"
    # insecure-skip-verify = true # if true, server certificates will not be validated

    [udp]
    listen = ":2003"
    enabled = false
    log-incomplete = false
    drop-future = "0s"
    drop-past = "0s"

    [tcp]
    listen = ":2003"
    enabled = false
    drop-future = "0s"
    drop-past = "0s"

    [pickle]
    listen = ":2004"
    enabled = false


    [prometheus]
    listen = ":2006"
    enabled = true
    drop-future = "0s"
    drop-past = "0s"

    [logging]
    logger = ""
    file = "stdout"
    level = "debug"
    encoding = "mixed"
    encoding-time = "iso8601"
    encoding-duration = "seconds"

    [convert_to_tagged]
    enabled = false
    separator = ""


---

{{- end}}