apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}-nodeexporter-deployment"
  namespace: click-graphite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - name: node-exporter
          image: prom/node-exporter:v1.2.2
          ports:
            - containerPort: 9100
              protocol: TCP

---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-nodeexporter-service"
  namespace: click-graphite
spec:
  selector:
    app: node-exporter
  ports:
    - name: "9100"
      protocol: TCP
      port: 9100
      targetPort: 9100
      nodePort: {{ .Values.nodeexporter.serverNodePort }}
  type: NodePort
