{{- if .Values.qryn.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
#   namespace: click
  name: qryn
  labels:
    io.metrico.service: qryn
spec:
  replicas: 1
  selector:
    matchLabels:
      io.metrico.service: qryn
  strategy: {}
  template:
    metadata:
      annotations:
        qryn.cmd: qryn.dev
      creationTimestamp: null
      labels:
        io.metrico.service: qryn
    spec:
      containers:
        - env:
            - name: CLICKHOUSE_AUTH #Авторизация в CH
              value: "{{ .Values.qryn.click.user }}:{{ .Values.qryn.click.password }}"
            - name: CLICKHOUSE_PORT #Порт CH
              value: "{{ .Values.qryn.click.port }}"
            - name: CLICKHOUSE_SERVER #Адрес сервера
              value: "{{ .Values.qryn.click.address }}"
          image: qxip/qryn
          name: qryn
          ports:
            - containerPort: 3100
          resources: {}
      restartPolicy: Always
status: {}

---
apiVersion: v1
kind: Service
metadata:
#   namespace: click
  creationTimestamp: null
  labels:
    io.metrico.service: qryn
  name: qryn
spec:
  ports:
    - name: "3100"
      port: 3100
      targetPort: 3100
  selector:
    io.metrico.service: qryn
status:
  loadBalancer: {}

{{- end }}
