{{- if .Values.zookeeper.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
  labels:
    app: zookeeper
spec:
  replicas: 1 # You can increase the replicas for a multi-node ZooKeeper ensemble
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: bitnami/zookeeper:latest # Use the version you prefer
          ports:
            - containerPort: 2181 # ZooKeeper client port
            - containerPort: 2888 # ZooKeeper peer communication port
            - containerPort: 3888 # ZooKeeper leader election port
          env:
            - name: ALLOW_ANONYMOUS_LOGIN
              value: "yes"
            - name: ZOO_MY_ID
              value: "1" # Each node in the ensemble should have a unique ID
            - name: ZOO_SERVERS
              value: "server.1=zookeeper-0:2888:3888"
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-service
spec:
  selector:
    app: zookeeper-service
  ports:
  - name: client
    port: 2181
    targetPort: 2181 
  - name: follower
    port: 2888
    targetPort: 2888 
  - name: leader
    port: 3888
    targetPort: 3888
  clusterIP: None 

{{- end }}